/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alpas1720
 */
public class game extends javax.swing.JFrame {
 Cards[]deck=new Cards[52];
 boolean[]deck2=new boolean[52];
 int totp=0;
 int totd=0;
 int cont=0;
 int ndrawp=2;
 int ndrawd=2;
 int covcard=0;
 int cartn=0;
 int cartnd=0;
    /**
     * Creates new form game
     */
    public game() {
        initComponents();
        deck2[0]=false;
        deck2[1]=false;
        deck2[2]=false;
        deck2[3]=false;
        deck2[4]=false;
        deck2[5]=false;
        deck2[6]=false;
        deck2[7]=false;
        deck2[8]=false;
        deck2[9]=false;
        deck2[10]=false;
        deck2[11]=false;
        deck2[12]=false;
        deck2[13]=false;
        deck2[14]=false;
        deck2[15]=false;
        deck2[16]=false;
        deck2[17]=false;
        deck2[18]=false;
        deck2[19]=false;
        deck2[20]=false;
        deck2[21]=false;
        deck2[22]=false;
        deck2[23]=false;
        deck2[23]=false;
        deck2[24]=false;
        deck2[25]=false;
        deck2[26]=false;
        deck2[27]=false;
        deck2[28]=false;
        deck2[29]=false;
        deck2[30]=false;
        deck2[31]=false;
        deck2[32]=false;
        deck2[33]=false;
        deck2[34]=false;
        deck2[35]=false;
        deck2[36]=false;
        deck2[37]=false;
        deck2[38]=false;
        deck2[39]=false;
        deck2[40]=false;
        deck2[41]=false;
        deck2[42]=false;
        deck2[43]=false;
        deck2[44]=false;
        deck2[45]=false;
        deck2[46]=false;
        deck2[47]=false;
        deck2[48]=false;
        deck2[49]=false;
        deck2[50]=false;
        deck2[51]=false;
        deck[0]=new Cards(1,"hearts","ace");
        deck[1]=new Cards(2,"hearts");
        deck[2]=new Cards(3,"hearts");
        deck[3]=new Cards(4,"hearts");
        deck[4]=new Cards(5,"hearts");
        deck[5]=new Cards(6,"hearts");
        deck[6]=new Cards(7,"hearts");
        deck[7]=new Cards(8,"hearts");
        deck[8]=new Cards(9,"hearts");
        deck[9]=new Cards(10,"hearts");
        deck[10]=new Cards(10,"hearts","jack");
        deck[11]=new Cards(10,"hearts","queen");
        deck[12]=new Cards(10,"hearts","queen");
        deck[13]=new Cards(1,"clubs","ace");
        deck[14]=new Cards(2,"clubs");
        deck[15]=new Cards(3,"clubs");
        deck[16]=new Cards(4,"clubs"); 
        deck[17]=new Cards(5,"clubs");
        deck[18]=new Cards(6,"clubs");
        deck[19]=new Cards(7,"clubs");
        deck[20]=new Cards(8,"clubs");
        deck[21]=new Cards(9,"clubs");
        deck[22]=new Cards(10,"clubs");
        deck[23]=new Cards(10,"clubs","jack");
        deck[24]=new Cards(10,"clubs","queen");
        deck[25]=new Cards(10,"clubs","queen");
        deck[26]=new Cards(1,"spades","ace");
        deck[27]=new Cards(2,"spades");
        deck[28]=new Cards(3,"spades");
        deck[29]=new Cards(4,"spades");
        deck[30]=new Cards(5,"spades");
        deck[31]=new Cards(6,"spades");
        deck[32]=new Cards(7,"spades");
        deck[33]=new Cards(8,"spades");
        deck[34]=new Cards(9,"spades");
        deck[35]=new Cards(10,"spades");
        deck[36]=new Cards(10,"spades","jack");
        deck[37]=new Cards(10,"spades","queen");
        deck[38]=new Cards(10,"spades","queen");
        deck[39]=new Cards(1,"diamonds","ace");
        deck[40]=new Cards(2,"diamonds");
        deck[41]=new Cards(3,"diamonds");
        deck[42]=new Cards(4,"diamonds");
        deck[43]=new Cards(5,"diamonds");
        deck[44]=new Cards(6,"diamonds");
        deck[45]=new Cards(7,"diamonds");
        deck[46]=new Cards(8,"diamonds");
        deck[47]=new Cards(9,"diamonds");
        deck[48]=new Cards(10,"diamonds");
        deck[49]=new Cards(10,"diamonds","jack");
        deck[50]=new Cards(10,"diamonds","queen");
        deck[51]=new Cards(10,"diamonds","queen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamepnl = new javax.swing.JPanel();
        dealertotlbl = new javax.swing.JLabel();
        dealertotnlbl = new javax.swing.JLabel();
        carddimlbl = new javax.swing.JLabel();
        dealercrdlbl = new javax.swing.JLabel();
        playertotlbl = new javax.swing.JLabel();
        playertotnlbl = new javax.swing.JLabel();
        playerlcrdlbl = new javax.swing.JLabel();
        cardpimlbl = new javax.swing.JLabel();
        drawbtn = new javax.swing.JButton();
        standbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        winlbl = new javax.swing.JLabel();
        lostlbl = new javax.swing.JLabel();
        startbtn = new javax.swing.JButton();
        dcardnlbl = new javax.swing.JLabel();
        pcardnlbl = new javax.swing.JLabel();
        cardpim2lbl = new javax.swing.JLabel();
        cardpim3lbl = new javax.swing.JLabel();
        cardpim4lbl = new javax.swing.JLabel();
        cardpim5lbl = new javax.swing.JLabel();
        cardd2lbl = new javax.swing.JLabel();
        cardd3lbl = new javax.swing.JLabel();
        cardd4lbl = new javax.swing.JLabel();
        cardd5lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gamepnl.setBackground(new java.awt.Color(0, 102, 51));

        dealertotlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dealertotlbl.setText("dealer total:");

        dealertotnlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dealercrdlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dealercrdlbl.setText("dealer's last card:");

        playertotlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playertotlbl.setText("your total:");

        playertotnlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        playerlcrdlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playerlcrdlbl.setText("your last card:");

        drawbtn.setText("draw");
        drawbtn.setEnabled(false);
        drawbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawbtnActionPerformed(evt);
            }
        });

        standbtn.setText("stand");
        standbtn.setEnabled(false);
        standbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standbtnActionPerformed(evt);
            }
        });

        resetbtn.setText("reset");
        resetbtn.setEnabled(false);
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        winlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lostlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        startbtn.setText("start");
        startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtnActionPerformed(evt);
            }
        });

        dcardnlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        pcardnlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout gamepnlLayout = new javax.swing.GroupLayout(gamepnl);
        gamepnl.setLayout(gamepnlLayout);
        gamepnlLayout.setHorizontalGroup(
            gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamepnlLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamepnlLayout.createSequentialGroup()
                        .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dealertotlbl)
                            .addComponent(dealertotnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dealercrdlbl))
                        .addGap(27, 27, 27)
                        .addComponent(carddimlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gamepnlLayout.createSequentialGroup()
                                .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drawbtn)
                                    .addComponent(standbtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(resetbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(startbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(gamepnlLayout.createSequentialGroup()
                                .addComponent(cardd3lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardd4lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(winlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lostlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardd5lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dcardnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gamepnlLayout.createSequentialGroup()
                        .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playertotlbl)
                            .addGroup(gamepnlLayout.createSequentialGroup()
                                .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playerlcrdlbl)
                                    .addComponent(playertotnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pcardnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cardpimlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cardpim2lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addComponent(cardpim3lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardpim4lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardpim5lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gamepnlLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(cardd2lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        gamepnlLayout.setVerticalGroup(
            gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamepnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamepnlLayout.createSequentialGroup()
                        .addComponent(dealertotlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dealertotnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(dealercrdlbl))
                    .addComponent(carddimlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cardd3lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardd2lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardd4lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addComponent(cardd5lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamepnlLayout.createSequentialGroup()
                        .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(drawbtn)
                                .addComponent(startbtn))
                            .addComponent(winlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lostlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(standbtn)
                                .addComponent(resetbtn)))
                        .addGap(35, 35, 35)
                        .addGroup(gamepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cardpim3lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardpim4lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardpim5lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cardpim2lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardpimlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gamepnlLayout.createSequentialGroup()
                        .addComponent(dcardnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(playertotlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playertotnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerlcrdlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pcardnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamepnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamepnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drawbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawbtnActionPerformed

        int ncard=(int)(Math.random()*51);
        while(deck2[ncard]){
        ncard=(int)(Math.random()*51);
        }
        deck2[ncard]=true;
        cartn++;
        if(cartn==1){
        cardpim3lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncard].getFamily()+"/"+deck[ncard].getRole()+".png")));
        }
        else if(cartn==2){
         cardpim4lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncard].getFamily()+"/"+deck[ncard].getRole()+".png")));
        }
        else if(cartn==3){
         cardpim5lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncard].getFamily()+"/"+deck[ncard].getRole()+".png")));   
        }
        int vcard=deck[ncard].getValue();
        totp=totp+vcard;
        playertotnlbl.setText(""+totp);
        pcardnlbl.setText(""+deck[ncard]);
        
        ndrawp++;
        if (totp==21){
         drawbtn.setEnabled(false);
         standbtn.setEnabled(false);
         winlbl.setText("You have won!");   
        }
        else if(totp>21){
         drawbtn.setEnabled(false);
         standbtn.setEnabled(false);
         lostlbl.setText("You have lost!");
        }
        if(ndrawp==5&&totp<=21){
          drawbtn.setEnabled(false);
          standbtn.setEnabled(false);  
          winlbl.setText("You have won!");     
        }
        
        
        
        
    }//GEN-LAST:event_drawbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
   totp=0;
   totd=0;
   cont=0;
   ndrawp=2;
   ndrawd=2;
   startbtn.setEnabled(true);
   drawbtn.setEnabled(false);
   standbtn.setEnabled(false);
   lostlbl.setText("");
   winlbl.setText("");
   dealertotnlbl.setText("");
   playertotnlbl.setText("");
   pcardnlbl.setText("");
   dcardnlbl.setText("");
   cardpimlbl.setIcon(null);
   cardpim2lbl.setIcon(null);
   cardpim3lbl.setIcon(null);
   cardpim4lbl.setIcon(null);
   cardpim5lbl.setIcon(null);
   carddimlbl.setIcon(null);
   cardd2lbl.setIcon(null);
   cardd3lbl.setIcon(null);
   cardd4lbl.setIcon(null);
   cardd5lbl.setIcon(null);
   cartn=0;
   cartnd=0;
   for(int i=0;i<=51;i++){
   deck2[i]=false;    
    }//GEN-LAST:event_resetbtnActionPerformed
}
    private void startbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtnActionPerformed
      int ncard1=(int)(Math.random()*51);
        while(deck2[ncard1]){
        ncard1=(int)(Math.random()*51);
        }
        deck2[ncard1]=true;    
        int vcard1=deck[ncard1].getValue();
        totp=totp+vcard1;
        cardpimlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncard1].getFamily()+"/"+deck[ncard1].getRole()+".png")));
        int ncard2=(int)(Math.random()*51);
        while(deck2[ncard2]){
        ncard2=(int)(Math.random()*51);
        }
        deck2[ncard2]=true;    
        int vcard2=deck[ncard2].getValue();
        cardpim2lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncard2].getFamily()+"/"+deck[ncard2].getRole()+".png")));
        totp=totp+vcard2;
        playertotnlbl.setText(""+totp);
        pcardnlbl.setText(""+deck[ncard2]);
        
        int ncardd1=(int)(Math.random()*51);
        while(deck2[ncardd1]){
        ncardd1=(int)(Math.random()*51);
        }
        deck2[ncardd1]=true;    
        int vcardd1=deck[ncardd1].getValue();
        totd=totd+vcardd1;
        carddimlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncardd1].getFamily()+"/"+deck[ncardd1].getRole()+".png")));
        dealertotnlbl.setText(vcardd1+"+?");
        dcardnlbl.setText(""+deck[ncardd1]);
        int ncardd2=(int)(Math.random()*51);
        while(deck2[ncardd2]){
        ncardd2=(int)(Math.random()*51);
        }
        deck2[ncardd2]=true;    
        int vcardd2=deck[ncardd2].getValue();
        totd=totd+vcardd2;
        covcard=ncardd2;
        
        startbtn.setEnabled(false);
        drawbtn.setEnabled(true);
        standbtn.setEnabled(true);
        resetbtn.setEnabled(true);
    }//GEN-LAST:event_startbtnActionPerformed

    private void standbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standbtnActionPerformed
        if(cont==0){
        drawbtn.setEnabled(false);
        dealertotnlbl.setText(""+totd);
        dcardnlbl.setText(""+deck[covcard]);
        cardd2lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[covcard].getFamily()+"/"+deck[covcard].getRole()+".png")));
        cont++;
        }
        else if(cont==1){
        if(totd<17){
        int ncardd=(int)(Math.random()*51);
        while(deck2[ncardd]){
        ncardd=(int)(Math.random()*51);
        }
        deck2[ncardd]=true;    
        int vcardd=deck[ncardd].getValue();
        totd=totd+vcardd;
        cartnd++;
         if(cartnd==1){
        cardd3lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncardd].getFamily()+"/"+deck[ncardd].getRole()+".png")));
        }
        else if(cartnd==2){
         cardd4lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncardd].getFamily()+"/"+deck[ncardd].getRole()+".png")));
        }
        else if(cartnd==3){
         cardd5lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+deck[ncardd].getFamily()+"/"+deck[ncardd].getRole()+".png")));   
        }
         
        dealertotnlbl.setText(""+totd);
        dcardnlbl.setText(""+deck[ncardd]);
        ndrawd++;
        if(ndrawd==5&&totd<=21){
           lostlbl.setText("You have lost!");  
        }
        if(totd==21){
            lostlbl.setText("You have lost!");
            standbtn.setEnabled(false);
        }
        if(totd>21){
            winlbl.setText("You have won!");
            standbtn.setEnabled(false);
        }
        }
        else{
         standbtn.setEnabled(false);
         if(totp<totd){
         lostlbl.setText("You have lost!");    
         }
         else if(totp>totd){
         winlbl.setText("You have won!");  
         }
         else{
            winlbl.setText("It's a tie!"); 
         }
        }
        }
        
        
        
    }//GEN-LAST:event_standbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardd2lbl;
    private javax.swing.JLabel cardd3lbl;
    private javax.swing.JLabel cardd4lbl;
    private javax.swing.JLabel cardd5lbl;
    private javax.swing.JLabel carddimlbl;
    private javax.swing.JLabel cardpim2lbl;
    private javax.swing.JLabel cardpim3lbl;
    private javax.swing.JLabel cardpim4lbl;
    private javax.swing.JLabel cardpim5lbl;
    private javax.swing.JLabel cardpimlbl;
    private javax.swing.JLabel dcardnlbl;
    private javax.swing.JLabel dealercrdlbl;
    private javax.swing.JLabel dealertotlbl;
    private javax.swing.JLabel dealertotnlbl;
    private javax.swing.JButton drawbtn;
    private javax.swing.JPanel gamepnl;
    private javax.swing.JLabel lostlbl;
    private javax.swing.JLabel pcardnlbl;
    private javax.swing.JLabel playerlcrdlbl;
    private javax.swing.JLabel playertotlbl;
    private javax.swing.JLabel playertotnlbl;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton standbtn;
    private javax.swing.JButton startbtn;
    private javax.swing.JLabel winlbl;
    // End of variables declaration//GEN-END:variables
}
